### ISSUE TITLE
Can no longer log in with OpenID 2.0

### ISSUE THREAD

**Issue by rstecker** [logV/snorkel#12]
:(  Most of us only got set up with the OpenID account... and now can't log in/make new accounts. There's no where in the UI to create a normal username/password account.  

What we get when we try to log in:
https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by okayzed** [comment]
google is bullshit. will fix

**Comment by okayzed** [comment]
for now, log in to the snorkel machine (wherever the source code resides) and find the dir that contains the 'scripts' dir. then run:

`bash scripts/add_user.sh rebecca` to add rebecca user (it will prompt you to enter a password)

**Comment by okayzed** [comment]
Alright, I pushed a fix for this, but... to install snorkel.sf at rdio requires building a package. Do you know how to do that? I Think there is some stuff in my home dir on the machines for it.

**Comment by okayzed** [comment]
rdio is no longer around, but this issue is fixed!
