### ISSUE TITLE
Can't start snorkel

### ISSUE THREAD

**Issue by mikramulhaq** [logv/snorkel#16]
@okayzed  I have been trying to start snorkel and tried like many different versions of node and other npm packages on both linux and mac. I have tried with sybil and mongo both.

It crashes on below when opening datasets page, let me know if you need additional info:

```
Listening for HTTP connections on port 3000
Listening for HTTPS connections on port 3443
Not using /etc/snorkel/config.js
Listening for incoming packets on UDP port 59036
Error lessing app/static/styles/bootstrap/overrides.css , sending uncompiled version

/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/engine.io/lib/server.js:171
  fn(null, true);
  ^
TypeError: Cannot read property 'handleUpgrade' of undefined
    at /Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/engine.io/lib/server.js:360:12
    at Server.verify (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/engine.io/lib/server.js:171:3)
    at Server.handleUpgrade (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/engine.io/lib/server.js:349:8)
    at child.upgrade (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/primus/transformers/engine.io/server.js:52:18)
    at child.emit (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/eventemitter3/index.js:91:35)
    at emitter (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/emits/index.js:26:22)
    at iterate (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/primus/transformer.js:125:24)
    at done (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/primus/transformer.js:139:7)
    at authorized (/Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/primus/middleware/authorization.js:26:24)
    at /Users/ikramulhaq/vms/logv-snorkel2/data/snorkel/snorkel/node_modules/superfluous/core/server/auth.js:87:17 
```

**Comment by okayzed** [comment]
hi, thanks for trying to run snorkel (and sorry for the difficulties). at first glance, it looks to be a problem with the engine.io module. let me take a look into it - what version of linux have you tried on? (I've been developing against ubuntu LTS (14.04 and 16.10, etc)

i will try a fresh clone and see what happens.

**Comment by okayzed** [comment]
I am able to reproduce the issue - i appreciate you reporting it. time to track it down and fix

**Comment by okayzed** [comment]
the issue is related to engine.io version 2.0.0. I've pinned a dependent package  (superfluous@0.66) to engine.io@1.5.0. If you reinstall superfluous (npm install superfluous) from inside snorkel subdir and verify that 0.66 is installed (which receives engine.io 1.5.0 as dependency), it should hopefully fix this issue. Alternatively, you can just blow away your node_modules dir and try again. 

for reference, other people had this issue with engine.io@2.0.0 as well.https://github.com/socketio/engine.io/issues/442

**Comment by okayzed** [comment]
I see that engine.io fixed this issue in 2.0.1 cdb487dbdcbf97e771e232fd65b594172fc947b5 released 2 hours ago.

I'm glad they moved quickly to resolve things. please feel free to close this issue (or keep updating it as you run into more problems). I will stay pinned at an earlier version of engine.io for a little while.

**Comment by mikramulhaq** [comment]
Thanks @okayzed for such a quick response. I'll try this out as soon as I get sometime (most likely today evening) and will close it or update it.

I worked in scuba team at facebook for about 2.5 years and like everyone else loved that product. Thanks for putting effort to make snorkel, hopefully I'll have it running soon for some vanilla scenarios soon. Demo and screenshots seem very awesome and promising.

Installing other modeules by hand was not difficult part at all.

**Comment by okayzed** [comment]
@mikramulhaq that's great! i'm glad that you (and the team) have worked hard to make scuba popular today. i was somewhat expecting an upstart 3 person team to deliver a better product at some point in the past few years, but the team has done a good job of defending the fort :-D

**Comment by mikramulhaq** [comment]
Thanks @okayzed, when I left scuba 5 months ago scuba team was > 10 people. Snorkel will be great as well I hope. 
Yes this issue is resolved, but there are couple of other issues we found. My friend @adilhafeez will create an issue for those.
