### ISSUE TITLE
src.util.time_to_seconds does not work with bsd date

### ISSUE THREAD

**Issue by tmc** [logv/snorkel#43]
bsd's date isn't quite as fancy as gnu's and the '-1 week' parsing doesn't work with it.

**Comment by okayzed** [comment]
should we find a python library that does this, then? coreutils is available on BSD, but it will lead to confusing situations to have special setup for BSD.

**Comment by okayzed** [comment]
`parsedatetime` is a python library that works here, i'm trying it out and verifying it works with common strings and py2/py3

**Comment by okayzed** [comment]
eab008d uses parsedatetime instead of `date` from coreutils
