### ISSUE TITLE
error responses are not rendered for the user

### ISSUE THREAD

**Issue by tmc** [logv/snorkel#44]
Example run_query response:
`{"__request__": {"activations": [], "css": []}, "cmp_644ad916a4": {"error": "('Unknown time string: ', u'-1 week')"}, "cmp_2aba949fda": {"activations": [], "html": [], "calls": []}, "__versions__": {}}`

these errors aren't rendered for the user.

**Comment by okayzed** [comment]
thanks! I'll add something for that this week

**Comment by okayzed** [comment]
4094af431c403c231992fceb50f7a35033aaee1f adds a simple modal dialog for errors. i tested it by supplying invalid times to the custom time inputs
